import turtle

SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 1000

turtle.setup(SCREEN_HEIGHT, SCREEN_WIDTH)

turtle.penup()
turtle.setheading(270)
turtle.forward(100)
turtle.setheading(0)
turtle.pendown()

turtle.pencolor('orange')
turtle.pensize(5)
turtle.circle(100)

turtle.penup()
turtle.setheading(15)
turtle.forward(50)
turtle.pendown()
turtle.pencolor('blue')
turtle.circle(100)

turtle.setheading(30)
turtle.penup()
turtle.forward(50)
turtle.pendown()
turtle.pencolor('yellow')
turtle.circle(100)

turtle.setheading(45)
turtle.penup()
turtle.forward(50)
turtle.pendown()
turtle.pencolor('red')
turtle.circle(100)

turtle.setheading(60)
turtle.penup()
turtle.forward(50)
turtle.pendown()
turtle.pencolor('purple')
turtle.circle(100)

turtle.setheading(75)
turtle.penup()
turtle.forward(50)
turtle.pendown()
turtle.pencolor('pink')
turtle.circle(100)

turtle.setheading(90)
turtle.penup()
turtle.forward(50)
turtle.pendown()
turtle.pencolor('turquoise')
turtle.circle(100)

turtle.setheading(105)
turtle.penup()
turtle.forward(50)
turtle.pendown()
turtle.pencolor('green')
turtle.circle(100)

turtle.penup()
turtle.setheading(120)
turtle.forward(50)
turtle.pendown()
turtle.pencolor('blue')
turtle.circle(100)

turtle.setheading(135)
turtle.penup()
turtle.forward(50)
turtle.pendown()
turtle.pencolor('yellow')
turtle.circle(100)

turtle.setheading(150)
turtle.penup()
turtle.forward(50)
turtle.pendown()
turtle.pencolor('red')
turtle.circle(100)

turtle.setheading(165)
turtle.penup()
turtle.forward(50)
turtle.pendown()
turtle.pencolor('purple')
turtle.circle(100)

turtle.setheading(180)
turtle.penup()
turtle.forward(50)
turtle.pendown()
turtle.pencolor('pink')
turtle.circle(100)

turtle.setheading(195)
turtle.penup()
turtle.forward(50)
turtle.pendown()
turtle.pencolor('turquoise')
turtle.circle(100)

turtle.setheading(210)
turtle.penup()
turtle.forward(50)
turtle.pendown()
turtle.pencolor('green')
turtle.circle(100)

turtle.penup()
turtle.setheading(225)
turtle.forward(50)
turtle.pendown()
turtle.pencolor('blue')
turtle.circle(100)

turtle.setheading(240)
turtle.penup()
turtle.forward(50)
turtle.pendown()
turtle.pencolor('yellow')
turtle.circle(100)

turtle.setheading(255)
turtle.penup()
turtle.forward(50)
turtle.pendown()
turtle.pencolor('red')
turtle.circle(100)

turtle.setheading(270)
turtle.penup()
turtle.forward(50)
turtle.pendown()
turtle.pencolor('purple')
turtle.circle(100)

turtle.setheading(285)
turtle.penup()
turtle.forward(50)
turtle.pendown()
turtle.pencolor('pink')
turtle.circle(100)

turtle.setheading(300)
turtle.penup()
turtle.forward(50)
turtle.pendown()
turtle.pencolor('brown')
turtle.circle(100)

turtle.setheading(315)
turtle.penup()
turtle.forward(50)
turtle.pendown()
turtle.pencolor('teal')
turtle.circle(100)

turtle.setheading(330)
turtle.penup()
turtle.forward(50)
turtle.pendown()
turtle.pencolor('maroon')
turtle.circle(100)

turtle.setheading(345)
turtle.penup()
turtle.forward(50)
turtle.pendown()
turtle.pencolor('grey')
turtle.circle(100)

turtle.xcor()
turtle.ycor()

turtle.done()