import turtle

#turtle.goto(0,100)
#turtle.goto(-100,0)
#turtle.goto(0,0)

#turtle.write('Hello World')

#turtle.setup(300, 300)
#turtle.penup()
#turtle.hideturtle()
#turtle.goto(-120, 120)
#turtle.write("Top Left")
#turtle.goto(70, -120)
#turtle.write("Bottom Right")


turtle.hideturtle()
turtle.fillcolor('pink')
turtle.begin_fill()
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.end_fill()

turtle.penup()
turtle.goto(-100,0)
turtle.pendown()
turtle.fillcolor('turquoise')
turtle.begin_fill()
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.end_fill()

turtle.penup()
turtle.goto(-100,100)
turtle.pendown()
turtle.setheading(0)
turtle.fillcolor('yellow')
turtle.begin_fill()
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.end_fill()

turtle.penup()
turtle.goto(100,-100)
turtle.pendown()
turtle.setheading(180)
turtle.fillcolor('green')
turtle.begin_fill()
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.end_fill()


turtle.done()