import turtle

turtle.hideturtle()

#setup screen size

turtle.setup(600, 600)

#draw first column of red circles

turtle.penup()
turtle.goto(-250,200)
turtle.pendown()
turtle.fillcolor('red')
turtle.begin_fill()
turtle.circle(50)
turtle.end_fill()

turtle.penup()
turtle.goto(-250,100)
turtle.pendown()
turtle.fillcolor('red')
turtle.begin_fill()
turtle.circle(50)
turtle.end_fill()

turtle.penup()
turtle.goto(-250,0)
turtle.pendown()
turtle.fillcolor('red')
turtle.begin_fill()
turtle.circle(50)
turtle.end_fill()


turtle.penup()
turtle.goto(-250,-100)
turtle.pendown()
turtle.fillcolor('red')
turtle.begin_fill()
turtle.circle(50)
turtle.end_fill()

turtle.penup()
turtle.goto(-250,-200)
turtle.pendown()
turtle.fillcolor('red')
turtle.begin_fill()
turtle.circle(50)
turtle.end_fill()

turtle.penup()
turtle.goto(-250,-300)
turtle.pendown()
turtle.fillcolor('red')
turtle.begin_fill()
turtle.circle(50)
turtle.end_fill()

#draw second column of green circles

turtle.penup()
turtle.goto(-150,200)
turtle.pendown()
turtle.fillcolor('green')
turtle.begin_fill()
turtle.circle(50)
turtle.end_fill()

turtle.penup()
turtle.goto(-150,100)
turtle.pendown()
turtle.fillcolor('green')
turtle.begin_fill()
turtle.circle(50)
turtle.end_fill()

turtle.penup()
turtle.goto(-150,0)
turtle.pendown()
turtle.fillcolor('green')
turtle.begin_fill()
turtle.circle(50)
turtle.end_fill()

turtle.penup()
turtle.goto(-150,-100)
turtle.pendown()
turtle.fillcolor('green')
turtle.begin_fill()
turtle.circle(50)
turtle.end_fill()

turtle.penup()
turtle.goto(-150,-200)
turtle.pendown()
turtle.fillcolor('green')
turtle.begin_fill()
turtle.circle(50)
turtle.end_fill()

turtle.penup()
turtle.goto(-150,-300)
turtle.pendown()
turtle.fillcolor('green')
turtle.begin_fill()
turtle.circle(50)
turtle.end_fill()

#draw 3rd column of blue circles

turtle.penup()
turtle.goto(-50,200)
turtle.pendown()
turtle.fillcolor('blue')
turtle.begin_fill()
turtle.circle(50)
turtle.end_fill()

turtle.penup()
turtle.goto(-50,100)
turtle.pendown()
turtle.fillcolor('blue')
turtle.begin_fill()
turtle.circle(50)
turtle.end_fill()

turtle.penup()
turtle.goto(-50,0)
turtle.pendown()
turtle.fillcolor('blue')
turtle.begin_fill()
turtle.circle(50)
turtle.end_fill()

turtle.penup()
turtle.goto(-50,-100)
turtle.pendown()
turtle.fillcolor('blue')
turtle.begin_fill()
turtle.circle(50)
turtle.end_fill()

turtle.penup()
turtle.goto(-50,-200)
turtle.pendown()
turtle.fillcolor('blue')
turtle.begin_fill()
turtle.circle(50)
turtle.end_fill()

turtle.penup()
turtle.goto(-50,-300)
turtle.pendown()
turtle.fillcolor('blue')
turtle.begin_fill()
turtle.circle(50)
turtle.end_fill()

#draw 4th column of red circles

turtle.penup()
turtle.goto(50,200)
turtle.pendown()
turtle.fillcolor('red')
turtle.begin_fill()
turtle.circle(50)
turtle.end_fill()

turtle.penup()
turtle.goto(50,100)
turtle.pendown()
turtle.fillcolor('red')
turtle.begin_fill()
turtle.circle(50)
turtle.end_fill()

turtle.penup()
turtle.goto(50,0)
turtle.pendown()
turtle.fillcolor('red')
turtle.begin_fill()
turtle.circle(50)
turtle.end_fill()

turtle.penup()
turtle.goto(50,-100)
turtle.pendown()
turtle.fillcolor('red')
turtle.begin_fill()
turtle.circle(50)
turtle.end_fill()

turtle.penup()
turtle.goto(50,-200)
turtle.pendown()
turtle.fillcolor('red')
turtle.begin_fill()
turtle.circle(50)
turtle.end_fill()

turtle.penup()
turtle.goto(50,-300)
turtle.pendown()
turtle.fillcolor('red')
turtle.begin_fill()
turtle.circle(50)
turtle.end_fill()

#draw 5th column of green circles

turtle.penup()
turtle.goto(150,200)
turtle.pendown()
turtle.fillcolor('green')
turtle.begin_fill()
turtle.circle(50)
turtle.end_fill()

turtle.penup()
turtle.goto(150,100)
turtle.pendown()
turtle.fillcolor('green')
turtle.begin_fill()
turtle.circle(50)
turtle.end_fill()

turtle.penup()
turtle.goto(150,0)
turtle.pendown()
turtle.fillcolor('green')
turtle.begin_fill()
turtle.circle(50)
turtle.end_fill()

turtle.penup()
turtle.goto(150,-100)
turtle.pendown()
turtle.fillcolor('green')
turtle.begin_fill()
turtle.circle(50)
turtle.end_fill()

turtle.penup()
turtle.goto(150,-200)
turtle.pendown()
turtle.fillcolor('green')
turtle.begin_fill()
turtle.circle(50)
turtle.end_fill()

turtle.penup()
turtle.goto(150,-300)
turtle.pendown()
turtle.fillcolor('green')
turtle.begin_fill()
turtle.circle(50)
turtle.end_fill()

#draw 6th column of blue circles

turtle.penup()
turtle.goto(250,200)
turtle.pendown()
turtle.fillcolor('blue')
turtle.begin_fill()
turtle.circle(50)
turtle.end_fill()

turtle.penup()
turtle.goto(250,100)
turtle.pendown()
turtle.fillcolor('blue')
turtle.begin_fill()
turtle.circle(50)
turtle.end_fill()

turtle.penup()
turtle.goto(250,0)
turtle.pendown()
turtle.fillcolor('blue')
turtle.begin_fill()
turtle.circle(50)
turtle.end_fill()

turtle.penup()
turtle.goto(250,-100)
turtle.pendown()
turtle.fillcolor('blue')
turtle.begin_fill()
turtle.circle(50)
turtle.end_fill()

turtle.penup()
turtle.goto(250,-200)
turtle.pendown()
turtle.fillcolor('blue')
turtle.begin_fill()
turtle.circle(50)
turtle.end_fill()

turtle.penup()
turtle.goto(250,-300)
turtle.pendown()
turtle.fillcolor('blue')
turtle.begin_fill()
turtle.circle(50)
turtle.end_fill()

turtle.done()